---
- name: Deploy Node.js app
  hosts: all
  become: yes
  vars:
    nodejs_v: 18
  tasks:
    - name: Update and upgrade system
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 3600
    - name: Install dependencies
      apt:
        pkg:
          - curl
          - rsync
          - nginx
          - supervisor
        state: present
      tags: install
    - name: "Add nodejs apt key"
      apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present
    - name: "Add nodejs {{ nodejs_v }}.x ppa for apt repo"
      apt_repository:
        repo: deb https://deb.nodesource.com/node_{{ nodejs_v }}.x bionic main
        update_cache: yes
    - name: "Install nodejs"
      apt:
        update_cache: yes
        name: nodejs
        state: present
    - name: Update npm globally
      npm:
        global: yes
        name: "{{ item }}"
        state: latest
      with_items:
        - npm
    - name: Set up application directory
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      with_items:
        - /opt/projects/roadtok8s/js/src/
        - /var/log/supervisor/roadtok8s/js/
    - name: Copy Node.js app to remote server
      synchronize:
        src: '{{ playbook_dir }}/../../src/'
        dest: /opt/projects/roadtok8s/js/src/
        recursive: yes
        delete: yes
    - name: Copy Package.json to remote server
      synchronize:
        src: '{{ playbook_dir }}/../../package.json'
        dest: /opt/projects/roadtok8s/js/package.json
        recursive: yes
        delete: yes
    - name: Install Node.js packages
      shell: |
        npm install
      args:
        executable: /bin/bash
        chdir: "/opt/projects/roadtok8s/js/"
    - name: Configure Node.js with supervisor
      copy:
        src: ../../conf/supervisor.conf
        dest: /etc/supervisor/conf.d/roadtok8s-js.conf
      notify: restart nginx
    - name: Configure nginx
      copy:
        src: ../../conf/nginx.conf
        dest: /etc/nginx/sites-available/roadtok8s-js
      notify: restart nginx
    - name: Enable nginx site
      command: ln -s /etc/nginx/sites-available/roadtok8s-js /etc/nginx/sites-enabled
      args:
        creates: /etc/nginx/sites-enabled/roadtok8s-js
    - name: Remove default nginx site
      file:
        path: "{{ item }}"
        state: absent
      notify: restart nginx
      with_items:
        - /etc/nginx/sites-enabled/default
        - /etc/nginx/sites-available/default
    - name: Update supervisor and start Node.js app
      command: "{{ item }}"
      with_items:
        - supervisorctl reread
        - supervisorctl update
        - supervisorctl restart roadtok8s-js

  handlers:
    - name: restart nginx
      systemd:
        name: nginx
        state: restarted
